# An app config, provided by App: http://github.com/stephencelis/app
---
development: &development
  loaded_at: <%= Time.zone.now.iso8601 %>
  # Example of nested data:
  # apis:
  #   braintree:
  #     :login: testapi
  #     :password: password1
 
test:
  <<: *development

production:
  loaded_at: <%= Time.zone.now.iso8601 %>
